### ISSUE TITLE
Split Mojo::Feed in Mojo::Feed::Reader and Mojo::Feed

### ISSUE THREAD

**Issue by mdom** [dotandimet/Mojo-Feed#2]
Hi, as discussed in pull request #1, it's probably a good idea to split Mojo::Feed in two seperate package. I had some time and started a [mojo_feed_reader branch](https://github.com/mdom/Mojo-Feed/tree/mojo_feed_reader). The branch may not pass test or even work at all, as my commits are more dictated by family life than code milestones. Sorry for that.

**Comment by dotandimet** [comment]
Ignore my comment in that branch, I missed that there were multiple commits.
